---
- name: "Upgrading full distro packages"
  ansible.builtin.apt:
    update_cache: true
    upgrade: "dist"

- name: "Installing required packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    packages:
      - {name: "sudo"} # To enable elevated command.
      - {name: "openssh-server"} # To enable SSH.
      - {name: "sshpass"}
      - {name: "qemu-guest-agent"} # To enhance Proxmox integration with the VM.
      - {name: "python3-pip"}
      - {name: "python-is-python3"}
      - {name: "pip"}
      - {name: "ethtool"} # To enable Wake-on-Lan.
      - {name: "traceroute"} # It helps debug network problems.
      - {name: "whois"} # To enable mkpasswd command.
      - {name: "libsecret-tools"}
      - {name: "net-tools"}
      - {name: "curl"}
      - {name: "tree"}
      - {name: "fail2ban"}
