---
- name: "Installing required packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    update_cache: true
    upgrade: "safe"
    packages:
      - {name: "sshpass"} # noninteractive ssh password provider.
      - {name: "libsecret-tools"} # Store and retrieve passwords.
      - {name: "ethtool"} # To enable Wake-on-Lan.
      - {name: "curl"} # Transfer a URL.
      - {name: "traceroute"} # It helps debug network problems.
      - {name: "whois"} # To enable mkpasswd command.
      - {name: "net-tools"} # A collection of programs that form the base set of the NET-3 networking.
      - {name: "tree"} # List contents of directories in a tree-like format.
      - {name: "uuid"} # Universally Unique Identifier Command-Line Tool.
      - {name: "ufw"} # A program for managing the firewall for the VM.
      - {name: "fail2ban"} # Is an intrusion prevention software framework.
